"""
generate_summary.py
Generates data/weekly_summary.md from current metrics
"""

import json
from datetime import datetime, timezone

METRICS_FILE  = "data/metrics.json"
DAILY_LOG     = "data/daily_log.json"
SUMMARY_FILE  = "data/weekly_summary.md"


def main():
    with open(METRICS_FILE) as f:
        metrics = json.load(f)

    with open(DAILY_LOG) as f:
        daily = json.load(f)

    now        = datetime.now(timezone.utc)
    week_label = now.strftime("Week of %B %d, %Y")
    updated    = now.strftime("%Y-%m-%d %H:%M UTC")

    # Last 7 days of activity
    recent = daily["entries"][:7]
    activity_lines = "\n".join(
        f"- **{e['date']}** — {e['commits']} commits | streak {e['streak']} days"
        for e in recent
    ) or "_No activity recorded yet._"

    summary = f"""# Weekly Summary

> Auto-generated by `generate_summary.py` — last updated {updated}

## {week_label}

### Stats
- **Total Commits (last 100 events):** {metrics['total_commits']}
- **Current Streak:** {metrics['current_streak']} days
- **Longest Streak:** {metrics['longest_streak']} days

### Last 7 Days
{activity_lines}
"""

    with open(SUMMARY_FILE, "w") as f:
        f.write(summary)

    print(f"✅ Weekly summary written to {SUMMARY_FILE}")


if __name__ == "__main__":
    main()
